Librerias

In [2]:
from __future__ import print_function, division

from builtins import range

import numpy as np

from datetime import datetime

In [3]:
# creamos dos vectores

a=np.array([1,2,3])

b=np.array([2,1,1])

print('vector a:', a)

print('vector b:' ,b)

vector a: [1 2 3]
vector b: [2 1 1]


In [4]:
# hacemos la suma entre vector, hay que notar que para algebra lineal se multiplican los
# mismas ubicaciones y se suman los total.
# en este caso sería: (1*2)+(2*1)+(3*1)
np.sum(a*b)

7

In [5]:
(a*b).sum()
#otra forma de hacer el mismo producto

7

In [6]:
# el vector por un escalar: 1*2|2*2|3*2
a*2

array([2, 4, 6])

In [7]:
#otra forma de hacer el el prodcuto entre lso vectores "a" y "b"
np.dot(a,b)

7

In [8]:
#armamos dos matrices
M=np.array([[1,4],[2,3],[1,3]])
print('matriz M: \n',M) #el comando "\n" es para dejar un renglon 

matriz M: 
 [[1 4]
 [2 3]
 [1 3]]


In [9]:
N=np.array([2,4])
print('matriz N: \n',N)

matriz N: 
 [2 4]


In [10]:
np.dot(M,N) 
# 1*2+4*4=2+16=18 |2*2+3*4 =4+12=16| 1*2+3*4=2+12=14

array([18, 16, 14])

In [11]:
# Seleccionamos el elemento de la 3era fila y la 2da columna de la matriz "M"
# en python los indices comienzan e 0 (cero)
M[2][1]

3

In [12]:
M[1][1] #sería el elemento de la 2da fila y la 2da columna

3

In [13]:
M[1][0] #sería el elemento de la 2da fila y la 1ra columna

2

In [14]:
#otras de las formas de acceder a los elementos seria de la siguiente amnera:
M[1,0]

2

In [15]:
# tambien se pueden usar los np.matrix() pero no es recomendable

M1=np.matrix([[1,4],[2,3],[1,3]])

M1

matrix([[1, 4],
        [2, 3],
        [1, 3]])

In [16]:
# para convertir la matriz en array 
M2=np.array(M1)

M2

array([[1, 4],
       [2, 3],
       [1, 3]])

In [17]:
# para trasponer:
M2.T

array([[1, 2, 1],
       [4, 3, 3]])

In [18]:
# para generar vectores completos de 0 (ceros), usamos la función "zeros(cantidad de elementos 0)"
Cero=np.zeros(10)

Cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# si fuera una matriz de 5x5

Cero=np.zeros((5,5))

Cero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#si quiero que sean 1s

UNOs=np.ones((5,5))

UNOs

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#y si los quiero generados aleatoriamente

Rand=np.random.random((5,5))

Rand

array([[0.21401154, 0.92330519, 0.2020833 , 0.95481447, 0.83371378],
       [0.76859208, 0.12762526, 0.38630867, 0.43136851, 0.52976119],
       [0.15914727, 0.95450739, 0.7742096 , 0.05744046, 0.68293155],
       [0.30593853, 0.38659021, 0.93813352, 0.54497249, 0.87855674],
       [0.89629358, 0.98207008, 0.16758935, 0.10859868, 0.00800203]])

In [23]:
#si necesitamos valores que se ajusten a la normalidad usamons "randn()"

Gauss=np.random.randn(5,5)

Gauss

array([[ 0.73549008,  0.19579569,  1.90845022, -0.04161147, -1.65601293],
       [ 0.32163409, -0.18768523, -1.15564541, -1.19475491,  0.79313837],
       [-0.21514104, -0.10930438,  0.37685016,  1.02712086,  0.1048489 ],
       [ 0.543882  , -1.25178385, -1.34102612, -1.75323926,  0.5711949 ],
       [ 0.17650955, -0.31461156,  1.07806143, -0.20013776,  0.85465304]])

In [24]:
# calcular la media y la varianza "mean()" - "var()"

print('media: ', Gauss.mean())

print('varianza: ', Gauss.var())

media:  -0.02933298516019986
varianza:  0.8346021625615474


In [25]:
#producto de vectores o matrices elemento a elemento (se usa mucho en DS) 

#recordemos nuestros vectores originales a=np.array([1,2,3]) y b=np.array([2,1,1])

a*b

#se puede hacer lo mismo con matrices pero deben ser del mismo rango

array([2, 2, 3])

In [28]:
#inversa de una matriz, recordemos que debe ser cuadrada: linalg.inv
#deifnomos la matriz
M=np.matrix([[1,4,2],[2,3,4],[1,3,1]])
M

matrix([[1, 4, 2],
        [2, 3, 4],
        [1, 3, 1]])

In [29]:
#hacemos la inverza de la matriz definida
Minv=np.linalg.inv(M)

Minv

matrix([[-1.8,  0.4,  2. ],
        [ 0.4, -0.2,  0. ],
        [ 0.6,  0.2, -1. ]])

In [34]:
#como verificacion, si multimplicamos la inversa por la matriz nos da I
Minv.dot(M)

matrix([[ 1.0000000e+00, -8.8817842e-16,  0.0000000e+00],
        [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [35]:
#tambien se puede hacer:
M.dot(Minv)

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [-1.11022302e-16,  5.55111512e-17,  1.00000000e+00]])

In [30]:
#el determinante de M es
np.linalg.det(M)

#Regla de Cramer
# 1 4 2 1 4
# 2 3 4 2 3
# 1 3 1 1 3

5.000000000000001

In [31]:
np.diag(M) #para obtener la diagonal de la matriz

array([1, 3, 1])

In [35]:
#el producto externo es (con a=array([1, 2, 3]) y b=array([2, 1, 1]))
print('a: ', a)
print('b: ', b)
c=np.outer(a,b)
print('\n c: ', c)


a:  [1 2 3]
b:  [2 1 1]

 c:  [[2 1 1]
 [4 2 2]
 [6 3 3]]


In [36]:
np.inner(a,b)  #es igual al np.dot

7

In [37]:
#la traza de una matriz es la suma de los elemetos de la diagonal
np.trace(M)

5

In [ ]:
#tambien sumando la diagonal se hace lo mismo

np.diag(M).sum()


De álgebra lineal, los autovalores y autovectores 



In [38]:
# si la matriz es simétrica (A=A.T) o hermitiana (A=A conjugada traspuesta) se usa np.eigh(A)

# sino se usa np.eig(A)

A=np.array([[2,3,4],[3,5,1],[4,1,2]])

A

array([[2, 3, 4],
       [3, 5, 1],
       [4, 1, 2]])

In [39]:
A.T

array([[2, 3, 4],
       [3, 5, 1],
       [4, 1, 2]])

In [40]:
np.linalg.eigh(A)

#Devuelve dos np.array

#el primero es un vector con los autovalores

#el otro es la matriz devuelta contiene los autovectores en las columnas

(array([-2.31482723,  2.8619783 ,  8.45284893]),
 array([[ 0.74045812,  0.31340961, -0.59455546],
        [-0.21670595, -0.72604549, -0.65260744],
        [-0.63620775,  0.61207219, -0.46968855]]))

In [46]:

#Para resolver sistemas de ecuaciones lineales entonces podriamos hacerlo, con el siguiente ejemplo

# 2 x1 + 3 x2 - 5 x3 = 2

# -3 x1 + 2 x2 - x3 = 3

# x1 - 3 x2 + 2 x3 = 1

A= np.array([[2,3,-5],[-3,2,-1],[1,-3,2]])
print('\n A: \n', A, '\n')
B= np.array([2,3,1])
print('\n B:\n', B, '\n')


 A: 
 [[ 2  3 -5]
 [-3  2 -1]
 [ 1 -3  2]] 


 B:
 [2 3 1] 



In [48]:
#resolvemos como siempre

X=np.linalg.inv(A).dot(B)
#obtenemnos la inversa de y multiiplicamos por B
X

array([-2., -3., -3.])

In [49]:
#esta operación ya existe y se llama np.linalg.solve()

np.linalg.solve(A,B)

array([-2., -3., -3.])

In [58]:
Z = np.dot(np.linalg.inv(A),B)
Z

array([-2., -3., -3.])